services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:${POSTGRES_PORT}"
    networks:
      - db-backend

#  backend:
#    build: ./
#    container_name: backend
#    depends_on:
#      - db
#    restart: always
#    env_file:
#      - .env
#    working_dir: /app
#    volumes:
#      - .:/app
#    command: ["fastapi", "dev"]
#    ports:
#      - "8000:8000"
#    networks:
#      - db-backend

networks:
  db-backend:
    driver: bridge

volumes:
    postgres-data: